### ISSUE TITLE
Nightly release doesn't seem to be uploaded?

### ISSUE THREAD

**Issue by abadger** [simutrans/pak128#16]
I was trying to diagnose why the mail trailers in simupak128-2.8.2-for123.zip don't seem to match with the source code in this git repo and ran into something else that doesn't seem to make sense.

github lists a [Nightly release](https://github.com/simutrans/pak128/releases/tag/Nightly) which was created in January of 2022.  I see a github workflow that should build that Nightly on every push to the master branch.  I see in the Actions tab that the workflow `[did run](https://github.com/simutrans/pak128/actions/workflows/pak128-nightly.yml)` with the last push in February 2023.  The logs for that Action have expired so I can't check for any obvious reason that the Release and the last commits don't match.  Am I misunderstanding something about how these pieces are supposed to fit together?

**Comment by Roboron3042** [comment]
If you check the date of the asset, it states it is from February 28th (last push). The release date and commit are not updated, but the assets are.

**Comment by Roboron3042** [comment]
I think I made it less confusing by including the date in the title in the release tag.

However, this didn't notify me of a new release in my tests and it did when I submitted it to this repository. Maybe I will have to undo it...
