### ISSUE TITLE
New trains

### ISSUE THREAD

**Issue by garro95** [simutrans/pak128#6]
In this issue I will suggest some real world trains recently introduced in Italy that could be added to the pakset.

### Hitachi Rock (AKA Caravaggio)
![](https://upload.wikimedia.org/wikipedia/commons/e/ee/ETR_521_presso_la_stazione_di_Padova.jpg)
A double deck EMU running since 2019
https://en.wikipedia.org/wiki/Caravaggio_(train)

### Alstom Pop (AKA Coradia Stream)
![](https://upload.wikimedia.org/wikipedia/commons/1/1f/Treno_Pop_Brindisi.jpg)
A single deck EMU for Regional or intercity service
The Regional version can run up to 160 km/h, while the Intercity can reach 200 km/h.
Running since 2019
(Sorry I have to link Italian Wikipedia because the page is missing on the English version) 
https://it.wikipedia.org/wiki/Alstom_Coradia#Coradia_Stream
https://it.wikipedia.org/wiki/Pop_(treno)

### Frecciarossa 1000 (AKA ETR 1000 AKA V300 Zefiro)
![](https://upload.wikimedia.org/wikipedia/commons/d/da/Bombardier_ETR_1000_05_Innotrans_2014.JPG)
A high speed EMU that can reach 400 km/h (360 km/h commercial speed). Running in Italy since 2015.
I have a pak file with this train that was published on the simutrans forum. Maybe the author is willing to contribute it to the official pakset.
https://en.wikipedia.org/wiki/Frecciarossa_1000

### AGV 575 (AKA .italo)
![](https://upload.wikimedia.org/wikipedia/commons/3/36/NTV_italo_AGV_09_%28Salerno%29.jpg)
A High speed EMU that can reach 360 km/h commercial speed. Running in Italy since 2012.
https://en.wikipedia.org/wiki/AGV_(train)

### Alstom Metropolis
![](https://upload.wikimedia.org/wikipedia/commons/f/f1/2_C830_in_KCD.JPG)
Running in many cities, e.g. TMB class 9000 in Barcelona. Amsterdam, Santo Domingo...
https://en.wikipedia.org/wiki/Alstom_Metropolis

### Hitachi Rail Italy Driverless Metro (formerly MAAB, Metropolitana Automatica AnsaldoBreda)
![](https://upload.wikimedia.org/wikipedia/commons/9/9f/Danishmetrotrain.jpg)
In service since 2002, operating in Copenhagen, Brescia, Milano, Roma and other cities.
https://en.wikipedia.org/wiki/Hitachi_Rail_Italy_Driverless_Metro

**Comment by prissi** [comment]
Please go to the forum (forum.simutrans.com) where an artist may read this or provide a patch to include them.
